:global:
  build:
    matrix:
      - GOOS: linux
        GOARCH: amd64
.travis.yml:
  sudo: true
  deploy:
    access_key_id: AKIAINMB43VSSPFZISAA
    secret_access_key:
      secure: XMcEGnoHjJmiZUxgZ7b64EaGd5Ywyb4/yrndv6fFnItrOvNVrIUQoS55yfhx4QkPeQPM76ob5szON09xSqjIUw8X8YbK6AZt7aSuYO05CeryJcbtO8VQhkkuQlwRquFW9vPKoKPdKSIpsYJbVOOZb7p42yiSVBR8GIvpZfsjUWzIcBZpyjKIRf2Zj1DjDQE4HgmlBu9+BF80uUUBGKugtfq8MWyUip5UfdOE33MmqCrKAqiU38OeyI1sPoX7m3CAaepAF10LvahqXhqYYhh/neg20IvLafEu/5gVemXmsoceKlBTdwAMxKk/Luw2VIrQSvJicX4tqnyNrx0VECQf50YHGZ+qJoufDNmYgld2x2dCmUueDswLHTC2nqglccSCNCmsetu4GwGkgYFXy4OXSkLkehgZ8KJqPKakbEvTLuMkMDg3jM147hA9rXQFhGYVYDyc/dTJtTz9tP4lXNaw3rLzAyHR0TmPv3VcMMUXo+sFEwh3IBymeGHm7thkw4Q17OYD6ZUO/dSbloCfUmikyexcmU0LrrX9XZf1fd5PZifk0UDIOWu75REEbk4oEImZWUDkdI616UtMWg7XN0RH2mTHdUonG1HXKQ4GLlE2WzGiJx2xlhY+hs7tbdCYVEokc1jmh0nH9/BDEvAFfJ0I4caqr1PcPTJ3KAqgitYBBH8=
    api_key:
      secure: g79wbFry2bmE56XQw10MySdP0Ehm+j56Xvk7kH5Zs+WOX2wlmW1++ca96W4ltd53U2sbp3gIyAt6iKHwWHjHcImrPbrHMZ8O6F9wNHHa3TqBtYx0LkyKpTx75LFFEEkggcIACZtWWRr+V596yEoeozZj3n6cuudGEamJaC64OY4mNO5bzHcIrULb9TR1k61eaSgGKQ+BsC+NfrG2fVj/lbMfpHUZx74uY2oXzqDhMvsMZbGPAKDvII+2HhnDZUU2ilyJzCo1nj52i92ER7ewclD4dLnVNeGLL7QcWURJoeko59Jyj5OLKFRIa7/LfHNEzc7+HDaeKwYSqRKoZ4TpmEt1LQbEZRPIQ7LeXTrfII+jEKTdXwRB5tBtH5xa8Fjmw+DdbjHNaiWiF3Kqrd92ubWF4I7t64iTv2mC3Ym41Ij/DEsABVuzmZu4kRix8WFklQC7eNkSSUSJaakWkWEVT4DYGtn4l1satWQPPh3CKA1UnqWjCFTADt48fOKF61b+aXpoPaOCiZVBwmvF9lWCMze1vaYGWSjAlccOLsJVhbe29k9ZJzGacbs141C9YvQvW4CZQFe/BUZ+Y07irhn3bpnN9kXXuwQYB6VZTa/G4d4M3dUemKNYGfuN/lpmQcutxF7+YEW8sLq28fnOegKxFWKQV/Cpt5ildHx5HD7F7OY=

